version: '3.5'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6.14
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./var/lib/mysql:/var/lib/mysql/
      - ./etc/mysql/conf.d:/etc/mysql/conf.d/
