version: '3.5'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6.17
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/mariadb/data:/var/lib/mysql/
      - /opt/docker/mariadb:/etc/mysql/conf.d/
